// seed_data_d.js — Parte D: Agronomía (C60-C63) + Técnicas (C64-C73) + Materias Comunes (Tronco Común, Idiomas, Electivas)
window.SEED_D={
carreras:[
['AGR-060','Ingeniería Agronómica','Ciencias Agronómicas'],
['AIN-061','Ingeniería Agroindustrial','Ciencias Agronómicas'],
['FOR-062','Ingeniería Forestal','Ciencias Agronómicas'],
['ACU-063','Ingeniería en Acuicultura','Ciencias Agronómicas'],
['TDS-064','Técnico en Desarrollo de Software','Carreras Técnicas'],
['THW-065','Técnico en Mantenimiento de Hardware','Carreras Técnicas'],
['TDG-066','Técnico en Diseño Gráfico Web','Carreras Técnicas'],
['TEN-067','Técnico en Enfermería','Carreras Técnicas'],
['TGA-068','Técnico en Gastronomía','Carreras Técnicas'],
['TMA-069','Técnico en Mecánica Automotriz','Carreras Técnicas'],
['TTU-070','Técnico en Turismo','Carreras Técnicas'],
['TMD-071','Técnico en Marketing Digital','Carreras Técnicas'],
['TCC-072','Técnico en Control de Calidad','Carreras Técnicas'],
['TAD-073','Técnico en Asistencia Dental','Carreras Técnicas'],
],
materias:[
['AGR-060','BOT-150','Botánica General y Sistemática'],
['AGR-060','EDA-200','Edafología (Suelos)'],
['AGR-060','FIS-254','Fisiología Vegetal'],
['AGR-060','GEN-302','Genética y Fitomejoramiento'],
['AGR-060','ENT-300','Entomología (Insectos)'],
['AGR-060','FIT-350','Fitopatología (Enfermedades)'],
['AGR-060','CUL-402','Cultivos Básicos, Agroindustriales y Frutales'],
['AGR-060','RIE-353','Riegos y Drenajes'],
['AGR-060','MEC-302','Mecanización Agrícola'],
['AGR-060','ECO-403','Economía y Administración Agrícola'],
['AGR-060','PRE-453','Agricultura de Precisión y Drones'],
['AGR-060','ORG-402','Agricultura Orgánica'],
['AGR-060','TOP-252','Topografía Agrícola'],
['AGR-060','MET-303','Agrometeorología'],
['AIN-061','QUI-252','Química de Productos Agropecuarios'],
['AIN-061','MIC-304','Microbiología Industrial'],
['AIN-061','OPE-354','Operaciones Unitarias Agroindustriales'],
['AIN-061','GRA-403','Procesamiento de Granos y Cereales'],
['AIN-061','FRU-401','Tecnología de Frutas y Hortalizas'],
['AIN-061','CAR-452','Tecnología de Cárnicos y Lácteos'],
['AIN-061','CAL-404','Gestión de Calidad e Inocuidad'],
['AIN-061','MAQ-354','Maquinaria Agroindustrial'],
['AIN-061','DIS-455','Diseño de Plantas Agroindustriales'],
['AIN-061','SUB-402','Aprovechamiento de Subproductos'],
['AIN-061','BIO-453','Biotecnología Alimentaria'],
['AIN-061','REF-353','Refrigeración Agroindustrial'],
['AIN-061','COM-359','Comercialización Agropecuaria'],
['AIN-061','ENV-402','Envase y Embalaje Agroindustrial'],
['FOR-062','DEN-202','Dendrología (Estudio de árboles)'],
['FOR-062','ECO-254','Ecología Forestal'],
['FOR-062','SIL-300','Silvicultura'],
['FOR-062','MEN-350','Mensura e Inventarios Forestales'],
['FOR-062','MAN-402','Manejo de Bosques y Cuencas'],
['FOR-062','PRO-356','Protección Forestal (Incendios y Plagas)'],
['FOR-062','TEC-403','Tecnología de la Madera'],
['FOR-062','AGR-402','Agroforestería'],
['FOR-062','LEG-406','Legislación Forestal'],
['FOR-062','SIG-354','Sistemas de Información Geográfica'],
['FOR-062','CER-452','Certificación Forestal'],
['FOR-062','VIV-302','Viveros Forestales'],
['FOR-062','RES-453','Restauración de Ecosistemas'],
['FOR-062','FAU-350','Fauna Silvestre y Caza'],
['ACU-063','BIO-205','Biología Acuática'],
['ACU-063','CAL-253','Calidad del Agua'],
['ACU-063','NUT-303','Nutrición de Organismos Acuáticos'],
['ACU-063','CUL-356','Cultivo de Peces (Piscicultura)'],
['ACU-063','CAM-404','Cultivo de Camarones (Carcinocultura)'],
['ACU-063','MOL-400','Cultivo de Moluscos'],
['ACU-063','PAT-356','Patología Acuícola'],
['ACU-063','ING-404','Ingeniería de Estanques y Sistemas de Recirculación'],
['ACU-063','REP-452','Reproducción y Larvicultura'],
['ACU-063','PRO-452','Procesamiento de Productos Pesqueros'],
['ACU-063','OCE-250','Oceanografía Básica'],
['ACU-063','ECO-405','Economía y Comercialización Acuícola'],
['ACU-063','SOS-452','Acuicultura Sostenible'],
['ACU-063','LEG-407','Legislación Pesquera'],
['TDS-064','LOG-100','Lógica de Programación'],
['TDS-064','PRG-202','Programación Java/C#'],
['TDS-064','WEB-152','Desarrollo Web (HTML, CSS, JS)'],
['TDS-064','BDD-202','Bases de Datos (SQL)'],
['TDS-064','APP-250','Desarrollo de Apps Móviles'],
['TDS-064','TES-300','Testing y QA (Aseguramiento de Calidad)'],
['TDS-064','GIT-150','Gestión de Repositorios (Git/GitHub)'],
['TDS-064','SCR-250','Metodologías Ágiles (Scrum)'],
['THW-065','ARQ-102','Arquitectura de Computadoras'],
['THW-065','MAN-155','Mantenimiento Preventivo y Correctivo'],
['THW-065','RED-202','Redes LAN/WLAN'],
['THW-065','SIS-155','Sistemas Operativos y Software Base'],
['THW-065','ELE-202','Electrónica Básica'],
['THW-065','REC-252','Recuperación de Datos'],
['THW-065','SER-302','Mantenimiento de Servidores'],
['THW-065','CCT-250','Instalación de Cámaras CCTV'],
['TDG-066','FUN-102','Fundamentos de Diseño'],
['TDG-066','DIS-155','Photoshop e Illustrator'],
['TDG-066','UIX-202','Diseño de Interfaces (UI/UX)'],
['TDG-066','MAQ-254','Maquetación Web'],
['TDG-066','ANI-252','Animación Web'],
['TDG-066','RED-204','Diseño para Redes Sociales'],
['TDG-066','VID-150','Edición Básica de Video'],
['TDG-066','CMS-200','Sistemas Gestores de Contenido (WordPress)'],
['TEN-067','ANA-102','Anatomía Básica'],
['TEN-067','ENF-155','Fundamentos de Enfermería'],
['TEN-067','COM-205','Enfermería Comunitaria'],
['TEN-067','FAR-155','Farmacología Básica'],
['TEN-067','PRI-102','Primeros Auxilios'],
['TEN-067','BIO-155','Bioseguridad Hospitalaria'],
['TEN-067','TOM-200','Toma de Muestras'],
['TEN-067','MAT-254','Atención Materno-Infantil Básica'],
['TGA-068','CUI-102','Técnicas Culinarias Básicas'],
['TGA-068','COC-200','Cocina Nacional e Internacional'],
['TGA-068','PAS-200','Pastelería y Panadería'],
['TGA-068','HIG-150','Higiene y Manipulación de Alimentos'],
['TGA-068','COS-254','Costos de Alimentos y Bebidas'],
['TGA-068','ENO-250','Enología y Maridaje (Básico)'],
['TGA-068','GAR-200','Garde Manger (Cocina Fría)'],
['TGA-068','MON-152','Montaje y Presentación de Platos'],
['TMA-069','MOT-152','Motores de Combustión Interna'],
['TMA-069','SIS-204','Sistemas de Frenos y Suspensión'],
['TMA-069','ELE-204','Sistema Eléctrico Automotriz'],
['TMA-069','INY-250','Inyección Electrónica'],
['TMA-069','DIA-300','Diagnóstico Automotriz (Scanner)'],
['TMA-069','AIR-250','Aire Acondicionado Automotriz'],
['TMA-069','TRA-303','Transmisiones Automáticas y Manuales'],
['TMA-069','HIB-350','Mecánica de Vehículos Híbridos'],
['TTU-070','GEO-104','Geografía Turística Nacional'],
['TTU-070','GUI-154','Técnicas de Guía Turístico'],
['TTU-070','ATE-155','Atención al Turista'],
['TTU-070','ING-202','Inglés Técnico Turístico'],
['TTU-070','PAQ-250','Diseño de Paquetes Turísticos'],
['TTU-070','AVE-200','Turismo de Aventura'],
['TTU-070','LEG-155','Legislación Turística Básica'],
['TTU-070','ANI-204','Animación Turística'],
['TMD-071','RED-155','Gestión de Redes Sociales'],
['TMD-071','SEO-200','SEO y SEM'],
['TMD-071','EMA-200','E-mail Marketing'],
['TMD-071','ANA-254','Analítica Web'],
['TMD-071','CON-258','Creación de Contenido Digital'],
['TMD-071','ADS-250','Publicidad en Facebook y Google Ads'],
['TMD-071','ECO-205','E-Commerce Básico'],
['TMD-071','INB-300','Inbound Marketing'],
['TCC-072','EST-155','Estadística para la Calidad'],
['TCC-072','ISO-200','Normas ISO 9001'],
['TCC-072','HER-200','Herramientas de Calidad'],
['TCC-072','MET-254','Metrología'],
['TCC-072','SEG-155','Seguridad Industrial'],
['TCC-072','CEP-250','Control Estadístico de Procesos'],
['TCC-072','AUD-305','Auditorías Internas de Calidad'],
['TCC-072','BPM-150','Buenas Prácticas de Manufactura'],
['TAD-073','ANA-104','Anatomía Dental Básica'],
['TAD-073','INS-157','Instrumental y Materiales Dentales'],
['TAD-073','RAD-204','Radiología Dental'],
['TAD-073','BIO-157','Bioseguridad y Esterilización'],
['TAD-073','ASI-200','Asistencia en el Sillón Dental'],
['TAD-073','RES-157','Manejo de Residuos Odontológicos'],
['TAD-073','ADM-204','Administración de Citas y Expedientes'],
['TAD-073','IMP-254','Toma de Impresiones Dentales'],
],
// Materias sin carrera = visibles para TODOS los alumnos
comunales:[
['EXP-100','Expresión Oral y Escrita'],
['MET-100','Metodología de la Investigación Científica'],
['REA-100','Realidad Nacional y Contemporánea'],
['ETI-200','Ética Profesional y Ciudadana'],
['FIL-100','Filosofía General'],
['SOC-100','Sociología General'],
['PSG-101','Psicología General'],
['ECO-108','Ecología y Medio Ambiente'],
['LID-102','Liderazgo y Desarrollo Personal'],
['CUL-155','Cultura de Paz y Derechos Humanos'],
['MAT-099','Matemática Básica Institucional'],
['INF-099','Informática Básica'],
['EMP-202','Emprendimiento e Innovación'],
['VAL-100','Formación de Valores'],
['ING-101','Inglés I: Principiante'],
['ING-102','Inglés II: Básico'],
['ING-103','Inglés III: Pre-Intermedio'],
['ING-104','Inglés IV: Intermedio'],
['ING-105','Inglés V: Intermedio Alto'],
['ING-106','Inglés VI: Avanzado / Conversacional'],
['ING-400','Preparación para TOEFL/IELTS'],
['FRA-101','Francés I: Básico'],
['FRA-102','Francés II: Intermedio'],
['JAP-101','Japonés I: Hiragana y Katakana'],
['JAP-102','Japonés II: Kanji Básico'],
['MAN-105','Mandarín I: Pinyin y Tonos'],
['POR-103','Portugués I: Básico'],
['LES-100','Lengua de Señas Básica'],
['BLK-400','Blockchain y Criptoactivos'],
['RVA-400','Realidad Virtual y Aumentada'],
['CUA-500','Computación Cuántica Básica'],
['CIB-450','Ciberseguridad Ofensiva (Hacking Ético)'],
['IOT-402','Internet de las Cosas (IoT) Aplicado'],
['BIG-400','Análisis de Big Data'],
['EIA-402','Ética en la Inteligencia Artificial'],
['TRD-450','Transformación Digital Empresarial'],
['UXI-302','Diseño de Experiencia de Usuario (UX/UI)'],
['SMC-453','Ciudades Inteligentes (Smart Cities)'],
['IMP-355','Impresión 3D y Manufactura Aditiva'],
['CIN-003','Apreciación Cinematográfica'],
['FIN-003','Finanzas Personales para Estudiantes'],
['GES-005','Gestión del Tiempo y Productividad'],
['ORA-001','Oratoria y Debate Competitivo'],
['FOT-005','Taller de Fotografía con Smartphones'],
['TEA-005','Taller de Teatro Universitario'],
['COR-005','Coro Universitario'],
['AJE-001','Taller de Ajedrez'],
['DEP-001','Selección de Fútbol'],
['DEP-002','Selección de Baloncesto'],
['DEP-003','Acondicionamiento Físico / Gimnasio'],
['PRI-005','Primeros Auxilios y Protección Civil'],
['NUT-005','Nutrición para la Vida Diaria'],
['LCO-001','Lenguaje Corporal y Comunicación No Verbal'],
]};
